### ISSUE TITLE
Weather Location

### ISSUE THREAD

**Issue by lukaerzen** [stuartajd/dasher#1]
If the location is not synced when the application is loaded it is then not displayed (null).

After 10 minutes though it does appear as the location is resynced.

**Comment by stuartajd** [comment]
When the initial server is started I assume the location is already set therefore when the first weather sync happens it doesn't display anything until after the 10 minute refresh. This can cause issues if the user doesn't correctly set their GeoLocation through the browser. 

Need to ensure that the locations are either defined for the first location or attempt to capture them repeatedly until something is captured or simply fall back to using IP address locations for the current user to get a basic form of location.

**Comment by stuartajd** [comment]
The server side issue has been resolved; when attempting to update the weather if the localStorage of the locX or locY are missing the server will emit 'location' until it gets a response with the updated locX & locY. When the server receives the data in the syncData it will update. The server will not get the local weather without this information.

**Comment by stuartajd** [comment]
This issue has been fixed.
